// modbusCodes.js

const modbusCodes = [
  // Tipologia 1: Allarmi
  { code: 500, description: "allarme generico", type: "boolean" },
  { code: 501, description: "allarme sonde macchina", type: "boolean" },
  { code: 502, description: "allarmi ingressi", type: "boolean" },
  { code: 503, description: "allarmi da logiche", type: "boolean" },
  { code: 504, description: "allarmi circuito frigo 1", type: "boolean" },
  { code: 505, description: "allarmi circuito frigo 2", type: "boolean" },
  { code: 506, description: "allarmi resettabili", type: "boolean" },
  { code: 507, description: "allarmi non resettabili", type: "boolean" },
  { code: 550, description: "guasto sonda CO2 ambiente", type: "boolean" },
  { code: 551, description: "guasto sonda VOC ambiente", type: "boolean" },
  {
    code: 552,
    description: "guasto sonda temperatura ambiente",
    type: "boolean",
  },
  {
    code: 553,
    description: "guasto sonda temperatura esterna",
    type: "boolean",
  },
  { code: 554, description: "guasto sonda temperatura acqua", type: "boolean" },
  {
    code: 555,
    description: "guasto sonda temperatura mandata",
    type: "boolean",
  },
  {
    code: 556,
    description: "guasto sonda temperatura protezione antigelo batt acqua",
    type: "boolean",
  },
  {
    code: 557,
    description: "guasto sonda temperatura sbrinamento recuperatore",
    type: "boolean",
  },
  { code: 558, description: "guasto sonda umidità ambiente", type: "boolean" },
  {
    code: 600,
    description: "allarme resistenze elettriche grave",
    type: "boolean",
  },
  {
    code: 601,
    description: "allarme resistenze elettriche lieve",
    type: "boolean",
  },
  { code: 602, description: "allarme fuga gas", type: "boolean" },
  { code: 603, description: "allarme ventilazione", type: "boolean" },
  { code: 604, description: "allarme ventilatore ricircolo", type: "boolean" },
  { code: 605, description: "allarme ventilatore estrazione", type: "boolean" },
  {
    code: 606,
    description: "allarme ventilatore condensazione",
    type: "boolean",
  },
  { code: 607, description: "allame flussostato grave", type: "boolean" },
  { code: 608, description: "allarme flussostato lieve", type: "boolean" },
  { code: 609, description: "allarme sequenza fasi", type: "boolean" },
  { code: 650, description: "segnalazione pulire filtri", type: "boolean" },
  {
    code: 651,
    description: "segnalazione pulire tubo ionizzatore",
    type: "boolean",
  },
  {
    code: 652,
    description: "segnalazione sostituire tubo ionizzatore",
    type: "boolean",
  },
  {
    code: 653,
    description: "allarme protezione antigelo batteria acqua",
    type: "boolean",
  },
  {
    code: 654,
    description: "allarme protezione batteria acqua lieve",
    type: "boolean",
  },
  {
    code: 655,
    description: "allarme alta temperatura acqua per on compressore",
    type: "boolean",
  },
  {
    code: 656,
    description: "allarme bassa temperatura per on compressore",
    type: "boolean",
  },
  {
    code: 657,
    description:
      "allarme antigelo batteria acqua kit controllo temperatura mandata grave",
    type: "boolean",
  },
  {
    code: 658,
    description:
      "allarme antigelo batteria acqua kit controllo temperatura mandata lieve",
    type: "boolean",
  },
  { code: 659, description: "allarme macchina scarica", type: "boolean" },
  {
    code: 660,
    description: "allarme mancanza comunicazione con display",
    type: "boolean",
  },
  {
    code: 661,
    description: "allarme mancanza comunicazione con ionizzatore",
    type: "boolean",
  },
  {
    code: 662,
    description: "allarme mancanza comunicazione modbus master",
    type: "boolean",
  },

  // Tipologia A: Variabili binarie - Macchina A
  { code: 1, description: "On / Off", type: "boolean" },
  { code: 2, description: "On effettivo", type: "boolean" },
  { code: 3, description: "Stagione", type: "boolean" },
  { code: 4, description: "Stagione effettiva", type: "boolean" },
  {
    code: 5,
    description: "Abilitazione fasce orarie su display macchina",
    type: "boolean",
  },
  { code: 6, description: "Deumidifica attiva", type: "boolean" },
  {
    code: 7,
    description: "Richiesta acqua per trattamento aria",
    type: "boolean",
  },
  { code: 8, description: "Warning filtri sporchi", type: "boolean" },
  { code: 9, description: "Allarme generico", type: "boolean" },
  { code: 10, description: "Reset allarmi", type: "boolean" },
  { code: 11, description: "Abilitazione deumidifica", type: "boolean" },
  { code: 12, description: "Abilitazione riscaldamento", type: "boolean" },
  { code: 13, description: "Abilitazione raffreddamento", type: "boolean" },
  {
    code: 14,
    description: "Abilitazione free-cooling\\heating",
    type: "boolean",
  },
  {
    code: 15,
    description: "Presenza riscaldamento dell’aria",
    type: "boolean",
  },
  {
    code: 16,
    description: "Presenza raffreddamento dell’aria",
    type: "boolean",
  },
  { code: 17, description: "Presenza recuperatore", type: "boolean" },
  { code: 18, description: "Presenza free-cooling\\heating", type: "boolean" },
  { code: 19, description: "Riscaldamento attivo", type: "boolean" },
  { code: 20, description: "Raffreddamento attivo", type: "boolean" },
  { code: 21, description: "Ricambio attivo", type: "boolean" },
  { code: 22, description: "Free-cooling\\heating attivo", type: "boolean" },
  { code: 23, description: "Sbrinamento attivo", type: "boolean" },
  {
    code: 24,
    description: "Abilitazione riduzione ventilazione",
    type: "boolean",
  },
  { code: 25, description: "Abilitazione umidifica", type: "boolean" },
  { code: 26, description: "Sbrinamento recuperatore attivo", type: "boolean" },
  { code: 27, description: "Presenza condensatore remoto", type: "boolean" },
  { code: 28, description: "Presenza valvola acqua", type: "boolean" },
  { code: 29, description: "Presenza valvola acqua on-off", type: "boolean" },
  {
    code: 30,
    description: "Presenza valvola acqua modulante",
    type: "boolean",
  },
  {
    code: 31,
    description: "Presenza e abilitazione batteria acqua calda",
    type: "boolean",
  },
  {
    code: 32,
    description: "Presenza e abilitazione batteria acqua fredda",
    type: "boolean",
  },
  { code: 33, description: "Presenza controllo temperatura", type: "boolean" },
  { code: 34, description: "On compressore 1", type: "boolean" },
  { code: 35, description: "On compressore 2", type: "boolean" },
  { code: 36, description: "On ventilatore mandata", type: "boolean" },
  { code: 37, description: "On resistenza elettriche", type: "boolean" },

  // Tipologia B: Variabili binarie - Macchina B
  { code: 1, description: "Unità ON", type: "boolean" },
  { code: 2, description: "Forzatura deumidifica", type: "boolean" },
  {
    code: 3,
    description: "Abilitazione forzatura deumidifica [1]",
    type: "boolean",
  },
  { code: 4, description: "Forzatura riscaldamento [2]", type: "boolean" },
  {
    code: 5,
    description: "Abilitazione forzatura riscaldamento [1]",
    type: "boolean",
  },
  { code: 6, description: "Reset allarmi", type: "boolean" },
  { code: 7, description: "Reset pulizia filtri", type: "boolean" },
  { code: 8, description: "Forzatura raffreddamento [2]", type: "boolean" },
  {
    code: 9,
    description: "Abilitazione forzatura raffreddamento [1]",
    type: "boolean",
  },
  { code: 10, description: "Stato compressore", type: "boolean" },
  { code: 11, description: "Stato valvola acqua", type: "boolean" },
  { code: 12, description: "Stato resistenza elettrica", type: "boolean" },
  { code: 13, description: "Presenza valvola acqua", type: "boolean" },
  { code: 14, description: "Presenza resistenza elettrica", type: "boolean" },
  { code: 15, description: "Presenza allarme", type: "boolean" },
  { code: 16, description: "Filtri da pulire", type: "boolean" },
  {
    code: 17,
    description: "Presenza ventilatori elettronici",
    type: "boolean",
  },
  {
    code: 18,
    description: "Presenza opzione sbrinamento gas caldo",
    type: "boolean",
  },
  { code: 19, description: "Allarme sonda", type: "boolean" },
  { code: 20, description: "Allarme alta pressione", type: "boolean" },
  { code: 21, description: "Allarme bassa pressione", type: "boolean" },
  { code: 22, description: "Allarme macchina scarica", type: "boolean" },
  {
    code: 23,
    description: "Allarme bassa temperatura per ON compressore",
    type: "boolean",
  },
  {
    code: 24,
    description: "Allarme sovratemperatura resistenza elettrica",
    type: "boolean",
  },
  {
    code: 25,
    description: "Allarme sovratemperatura resistenza elettrica",
    type: "boolean",
  },
  { code: 26, description: "Allarme ventilatore", type: "boolean" },
  { code: 27, description: "Sbrinamento attivo", type: "boolean" },
  { code: 28, description: "Richiesta deumidifica", type: "boolean" },
  { code: 29, description: "Richiesta riscaldamento", type: "boolean" },
  { code: 30, description: "Richiesta raffreddamento", type: "boolean" },

  // Tipologia A: Variabili analogiche - Macchina A
  { code: 1, description: "Temperatura esterna", type: "float" },
  { code: 2, description: "Temperatura ambiente", type: "float" },
  { code: 3, description: "Temperatura mandata", type: "float" },
  { code: 4, description: "Temperatura ritorno", type: "float" },
  { code: 5, description: "Temperatura refrigerante entrata", type: "float" },
  { code: 6, description: "Temperatura refrigerante uscita", type: "float" },
  {
    code: 7,
    description: "Temperatura acqua batteria acqua calda",
    type: "float",
  },
  {
    code: 8,
    description: "Temperatura acqua batteria acqua fredda",
    type: "float",
  },
  {
    code: 9,
    description: "Temperatura acqua batteria acqua precaldata",
    type: "float",
  },
  { code: 10, description: "Temperatura uscita", type: "float" },
  { code: 11, description: "Temperatura delta uscita", type: "float" },
  {
    code: 12,
    description: "Temperatura ingresso serpentina di scarico",
    type: "float",
  },
  {
    code: 13,
    description: "Temperatura uscita serpentina di scarico",
    type: "float",
  },
  { code: 14, description: "Umidità relativa", type: "float" },
  { code: 15, description: "Pressione di mandata", type: "float" },
  { code: 16, description: "Pressione di ritorno", type: "float" },
  { code: 17, description: "Pressione bassa refrigerante", type: "float" },
  { code: 18, description: "Pressione alta refrigerante", type: "float" },
  { code: 19, description: "Pressione caldaia", type: "float" },
  { code: 20, description: "Pressione batteria acqua", type: "float" },
  { code: 21, description: "Portata refrigerante", type: "float" },
  {
    code: 22,
    description: "Portata acqua batteria acqua calda",
    type: "float",
  },
  {
    code: 23,
    description: "Portata acqua batteria acqua fredda",
    type: "float",
  },
  {
    code: 24,
    description: "Portata acqua batteria acqua precaldata",
    type: "float",
  },
  { code: 25, description: "Portata ventilatore mandata", type: "float" },
  { code: 26, description: "Portata ventilatore estrazione", type: "float" },
  { code: 27, description: "Portata ventilatore recupero", type: "float" },
  {
    code: 28,
    description: "Portata ventilatore in ingresso batteria acqua calda",
    type: "float",
  },
  {
    code: 29,
    description: "Portata ventilatore in ingresso batteria acqua fredda",
    type: "float",
  },
  {
    code: 30,
    description: "Portata ventilatore in ingresso batteria acqua precaldata",
    type: "float",
  },
  { code: 31, description: "Portata aria esterna", type: "float" },
  { code: 32, description: "Portata ricircolo", type: "float" },
  { code: 33, description: "Portata aria estrazione", type: "float" },
  { code: 34, description: "Portata aria esterna filtrata", type: "float" },
  { code: 35, description: "Portata batteria acqua calda", type: "float" },
  { code: 36, description: "Portata batteria acqua fredda", type: "float" },
  { code: 37, description: "Portata batteria acqua precaldata", type: "float" },
  { code: 38, description: "Portata serpentina di scarico", type: "float" },
  { code: 39, description: "Portata aria uscita", type: "float" },
  {
    code: 40,
    description: "Portata aria in mandata batteria acqua calda",
    type: "float",
  },
  {
    code: 41,
    description: "Portata aria in mandata batteria acqua fredda",
    type: "float",
  },
  {
    code: 42,
    description: "Portata aria in mandata batteria acqua precaldata",
    type: "float",
  },
  {
    code: 43,
    description: "Pressione portata batteria acqua calda",
    type: "float",
  },
  {
    code: 44,
    description: "Pressione portata batteria acqua fredda",
    type: "float",
  },
  {
    code: 45,
    description: "Pressione portata batteria acqua precaldata",
    type: "float",
  },
  {
    code: 46,
    description: "Pressione ritorno batteria acqua calda",
    type: "float",
  },
  {
    code: 47,
    description: "Pressione ritorno batteria acqua fredda",
    type: "float",
  },
  {
    code: 48,
    description: "Pressione ritorno batteria acqua precaldata",
    type: "float",
  },
  {
    code: 49,
    description: "Pressione alta batteria acqua calda",
    type: "float",
  },
  {
    code: 50,
    description: "Pressione alta batteria acqua fredda",
    type: "float",
  },
  {
    code: 51,
    description: "Pressione alta batteria acqua precaldata",
    type: "float",
  },
  {
    code: 52,
    description: "Pressione bassa batteria acqua calda",
    type: "float",
  },
  {
    code: 53,
    description: "Pressione bassa batteria acqua fredda",
    type: "float",
  },
  {
    code: 54,
    description: "Pressione bassa batteria acqua precaldata",
    type: "float",
  },
  {
    code: 55,
    description: "Pressione bassa refrigerante compressore 1",
    type: "float",
  },
  {
    code: 56,
    description: "Pressione alta refrigerante compressore 1",
    type: "float",
  },
  {
    code: 57,
    description: "Pressione bassa refrigerante compressore 2",
    type: "float",
  },
  {
    code: 58,
    description: "Pressione alta refrigerante compressore 2",
    type: "float",
  },
  { code: 59, description: "Portata acqua caldaia", type: "float" },
  { code: 60, description: "Pressione acqua caldaia", type: "float" },
  { code: 61, description: "Temperatura acqua caldaia", type: "float" },
  { code: 62, description: "Pressione aria esterna", type: "float" },
  {
    code: 63,
    description: "Pressione aria in mandata batteria acqua calda",
    type: "float",
  },
  {
    code: 64,
    description: "Pressione aria in mandata batteria acqua fredda",
    type: "float",
  },
  {
    code: 65,
    description: "Pressione aria in mandata batteria acqua precaldata",
    type: "float",
  },
  { code: 66, description: "Portata gas", type: "float" },
  { code: 67, description: "Pressione gas", type: "float" },
  { code: 68, description: "Temperatura gas", type: "float" },

  // Tipologia B: Variabili analogiche - Macchina B
  { code: 1, description: "Temperatura mandata", type: "float" },
  { code: 2, description: "Temperatura acqua mandata", type: "float" },
  { code: 3, description: "Temperatura ambiente", type: "float" },
  { code: 4, description: "Temperatura ritorno", type: "float" },
  { code: 5, description: "Temperatura uscita", type: "float" },
  { code: 6, description: "Temperatura esterna", type: "float" },
  { code: 7, description: "Pressione mandata", type: "float" },
  { code: 8, description: "Pressione ritorno", type: "float" },
  { code: 9, description: "Portata mandata", type: "float" },
  { code: 10, description: "Portata ritorno", type: "float" },
  { code: 11, description: "Portata batteria acqua calda", type: "float" },
  { code: 12, description: "Portata batteria acqua fredda", type: "float" },
  { code: 13, description: "Portata batteria acqua precaldata", type: "float" },
  { code: 14, description: "Pressione batteria acqua calda", type: "float" },
  { code: 15, description: "Pressione batteria acqua fredda", type: "float" },
  {
    code: 16,
    description: "Pressione batteria acqua precaldata",
    type: "float",
  },
  {
    code: 17,
    description: "Pressione uscita batteria acqua calda",
    type: "float",
  },
  {
    code: 18,
    description: "Pressione uscita batteria acqua fredda",
    type: "float",
  },
  {
    code: 19,
    description: "Pressione uscita batteria acqua precaldata",
    type: "float",
  },
  { code: 20, description: "Temperatura serpentina uscita", type: "float" },
  { code: 21, description: "Temperatura serpentina entrata", type: "float" },
  { code: 22, description: "Umidità relativa", type: "float" },
  { code: 23, description: "Portata aria esterna", type: "float" },
  { code: 24, description: "Portata batteria acqua calda", type: "float" },
  { code: 25, description: "Portata batteria acqua fredda", type: "float" },
  { code: 26, description: "Portata batteria acqua precaldata", type: "float" },
  { code: 27, description: "Portata serpentina di scarico", type: "float" },
  { code: 28, description: "Portata ventilatore mandata", type: "float" },
  { code: 29, description: "Portata ventilatore estrazione", type: "float" },
  { code: 30, description: "Portata ventilatore recupero", type: "float" },
  {
    code: 31,
    description: "Portata ventilatore in ingresso batteria acqua calda",
    type: "float",
  },
  {
    code: 32,
    description: "Portata ventilatore in ingresso batteria acqua fredda",
    type: "float",
  },
  {
    code: 33,
    description: "Portata ventilatore in ingresso batteria acqua precaldata",
    type: "float",
  },
  { code: 34, description: "Portata aria esterna filtrata", type: "float" },
  { code: 35, description: "Portata serpentina di scarico", type: "float" },
  { code: 36, description: "Portata aria uscita", type: "float" },
  {
    code: 37,
    description: "Portata aria in mandata batteria acqua calda",
    type: "float",
  },
];

module.exports = { modbusCodes };
